### ISSUE TITLE
Unable to find explicit activity class {in.example.com/com.aditya.filebrowser.FileBrowser}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by jitesh68** [adityak368/FileBrowser#14]
Fatal Exception: android.content.ActivityNotFoundException: Unable to find explicit activity class {in.transmr.daxfer/com.aditya.filebrowser.FileBrowser}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
       at android.app.Activity.startActivityForResult(Activity.java:3745)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
       at android.app.Activity.startActivityForResult(Activity.java:3706)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
       at android.app.Activity.startActivity(Activity.java:4016)
       at android.app.Activity.startActivity(Activity.java:3984)
       at in.transmr.daxfer.activity.MainActivity.onNavigationItemSelected(MainActivity.java:1119)
       at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:170)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
       at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:352)
       at android.view.View.performClick(View.java:4780)
       at android.view.View$PerformClick.run(View.java:19866)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by adityak368** [comment]
Can you provide more information on your library usage? Closing the issue until further update
