### ISSUE TITLE
Library crashes when user clicks on "Ext" button

### ISSUE THREAD

**Issue by AlexDibrivnyy** [adityak368/FileBrowser#4]
Wanted to use it on my app, but library crashes when I press on "Ext" button. Log file is attached below.
Phone is Nexus 5X.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
                                                                               at com.aditya.filebrowser.FileChooser.updateUI(FileChooser.java:243)
                                                                               at com.aditya.filebrowser.NavigationHelper.updateObservers(NavigationHelper.java:136)
                                                                               at com.aditya.filebrowser.NavigationHelper.navigateToExternalStorage(NavigationHelper.java:58)
                                                                               at com.aditya.filebrowser.listeners.TabChangeListener.handleTabChange(TabChangeListener.java:69)
                                                                               at com.aditya.filebrowser.listeners.TabChangeListener.onTabSelected(TabChangeListener.java:52)
                                                                               at com.roughike.bottombar.BottomBar.updateSelectedTab(BottomBar.java:949)
                                                                               at com.roughike.bottombar.BottomBar.handleClick(BottomBar.java:926)
                                                                               at com.roughike.bottombar.BottomBar.onClick(BottomBar.java:893)
                                                                               at android.view.View.performClick(View.java:5637)
                                                                               at android.view.View$PerformClick.run(View.java:22429)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by adityak368** [comment]
Thanks for the bug report. I will look into the issue and update with a fix asap. In the meantime can you please let me know which version of the library are u using? I am asking this because there is no button named ext in v1.2. it just has the icon in v1.2

**Comment by adityak368** [comment]
I have updated the version to v1.3. Please check in the version and let me know if it is fixed

**Comment by AlexDibrivnyy** [comment]
Hi @adityak368 , I used v1.2. 
I just checked and new version works fine. _You can close the issue._
Thank you.

**Comment by adityak368** [comment]
Thanks for the reply
